version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_development
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    ports:
      - '3000:3000'

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nest-db
      MYSQL_USER: nest-user
      MYSQL_PASSWORD: nest-pass
      MYSQL_ROOT_PASSWORD: nest-pass
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'

volumes:
  mysql-data:
    driver: local