name: Test

on:
  push:
    branches-ignore:
      - master
      - staging
      - production

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout pushed commit
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: restore env file
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" | sudo gpg --batch --passphrase-fd 0 --output ".env" --decrypt "env/.env.gpg"

      - name: restore test-env file
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" | sudo gpg --batch --passphrase-fd 0 --output ".env.test" --decrypt "env/.env.ci-test.gpg"

      - name: run test on docker-compose
        run: |
          docker-compose -f ./docker/test/docker-compose-test.yml up --abort-on-container-exit
